desc "criando banco"
task :migrations do
  #sh('rails db:environment:set RAILS_ENV=development')
  sh('rails db:create')
  sh('rails db:drop')
  sh('rails db:create')
  sh('rails d scaffold stundent')
  sh('rails g scaffold stundent name:string birth:date')
  #sh('rails d scaffold organization_device')
  # sh('rails d scaffold plan')
  # sh('rails d scaffold promo')
  # sh('rails d scaffold product')
  # sh('rails d scaffold promo_product_info')
  # sh('rails d scaffold rule')
  # sh('rails d scaffold coupon')
  # sh('rails d scaffold category')
  # sh('rails d scaffold super_category')
  # sh('rails g scaffold category name:string')
  # sh('rails g scaffold super_category name:string')
  # sh('rails g scaffold organization name:string super_category:references')
  # sh('rails g scaffold organization_device organization:references uuid:string')
  # sh('rails g scaffold plan plan_type:integer fee:decimal organization:references')
  # sh('rails g scaffold promo title:string description:string organization:references value:decimal coupon_amount:integer expiration:datetime')
  # sh('rails g scaffold product name:string description:string price:decimal category:references')
  # sh('rails g scaffold promo_product_info promo:references product:references product_amount:integer')
  # sh('rails g scaffold rule rule_type:integer promo:references')
  # sh('rails g scaffold coupon promo:references cod:string state:integer device_uuid:string')
  sh('rails db:migrate')
end
