default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    adapter: postgresql
    database: primary_educa_dev
    pool: 5
    timeout: 5000
  primary_replica:
    <<: *default
    database: db/primary_replica_educa_dev.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  primary:
    adapter: postgresql
    database: primary_educa_prod
    pool: 5
    timeout: 5000
  primary_replica:
    <<: *default
    database: db/primary_replica_educa_dev.sqlite3
